export const data = {
  businesses: [
    {
      id: "X8ZS-dgiMIJvhwf9SaDnjw",
      alias: "wah-fung-no-1-new-york-2",
      name: "Wah Fung No 1",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/KneHCoY6vhFMcQ6ZWZ0J3g/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/wah-fung-no-1-new-york-2?adjust_creative=57XI6Kzufv1Z91q9LwdlrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=57XI6Kzufv1Z91q9LwdlrQ",
      review_count: 2248,
      categories: [
        {
          alias: "hotdogs",
          title: "Fast Food",
        },
        {
          alias: "cantonese",
          title: "Cantonese",
        },
      ],
      rating: 4.4,
      coordinates: {
        latitude: 40.71735,
        longitude: -73.99457,
      },
      transactions: ["delivery"],
      price: "$",
      location: {
        address1: "79 Chrystie St",
        address2: "",
        address3: "",
        city: "New York",
        zip_code: "10002",
        country: "US",
        state: "NY",
        display_address: ["79 Chrystie St", "New York, NY 10002"],
      },
      phone: "+12129255175",
      display_phone: "(212) 925-5175",
      distance: 1312.163419247579,
      business_hours: [
        {
          open: [
            {
              is_overnight: false,
              start: "0900",
              end: "1900",
              day: 1,
            },
            {
              is_overnight: false,
              start: "0900",
              end: "1900",
              day: 2,
            },
            {
              is_overnight: false,
              start: "0900",
              end: "1900",
              day: 3,
            },
            {
              is_overnight: false,
              start: "0900",
              end: "1900",
              day: 4,
            },
            {
              is_overnight: false,
              start: "0900",
              end: "1900",
              day: 5,
            },
            {
              is_overnight: false,
              start: "0900",
              end: "1900",
              day: 6,
            },
          ],
          hours_type: "REGULAR",
          is_open_now: true,
        },
      ],
      attributes: {
        business_temp_closed: null,
        menu_url: "https://wah-fung.com/menu",
        open24_hours: null,
        waitlist_reservation: null,
      },
    },
    {
      id: "lynQoI3w_pzYfHGeuUU-Qg",
      alias: "shu-jiao-fu-zhou-new-york-2",
      name: "Shu Jiao Fu Zhou",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/9nywiaJs1Nq7HKNz-v_Tww/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/shu-jiao-fu-zhou-new-york-2?adjust_creative=57XI6Kzufv1Z91q9LwdlrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=57XI6Kzufv1Z91q9LwdlrQ",
      review_count: 1531,
      categories: [
        {
          alias: "chinese",
          title: "Chinese",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 40.7174109,
        longitude: -73.99208827387251,
      },
      transactions: ["pickup", "delivery"],
      price: "$",
      location: {
        address1: "295 Grand St",
        address2: null,
        address3: null,
        city: "New York",
        zip_code: "10002",
        country: "US",
        state: "NY",
        display_address: ["295 Grand St", "New York, NY 10002"],
      },
      phone: "+12126252532",
      display_phone: "(212) 625-2532",
      distance: 1332.0681618970148,
      business_hours: [
        {
          open: [
            {
              is_overnight: false,
              start: "0830",
              end: "2000",
              day: 0,
            },
            {
              is_overnight: false,
              start: "0830",
              end: "2000",
              day: 1,
            },
            {
              is_overnight: false,
              start: "0830",
              end: "2000",
              day: 2,
            },
            {
              is_overnight: false,
              start: "0830",
              end: "2000",
              day: 3,
            },
            {
              is_overnight: false,
              start: "0830",
              end: "2000",
              day: 4,
            },
            {
              is_overnight: false,
              start: "0830",
              end: "2000",
              day: 5,
            },
            {
              is_overnight: false,
              start: "0830",
              end: "2000",
              day: 6,
            },
          ],
          hours_type: "REGULAR",
          is_open_now: true,
        },
      ],
      attributes: {
        business_temp_closed: null,
        menu_url: "https://shujiaofuzhou.store/menu",
        open24_hours: null,
        waitlist_reservation: null,
      },
    },
    {
      id: "9-vKFnUby_6-pR6UJxjzMw",
      alias: "sun-hing-lung-new-york-2",
      name: "Sun Hing Lung ",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/a7PSHyXttSMaKi-9hqLL8Q/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/sun-hing-lung-new-york-2?adjust_creative=57XI6Kzufv1Z91q9LwdlrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=57XI6Kzufv1Z91q9LwdlrQ",
      review_count: 300,
      categories: [
        {
          alias: "chinese",
          title: "Chinese",
        },
      ],
      rating: 4.4,
      coordinates: {
        latitude: 40.7127362,
        longitude: -73.9950764600962,
      },
      transactions: [],
      price: "$",
      location: {
        address1: "58 Henry St",
        address2: "",
        address3: "",
        city: "New York",
        zip_code: "10002",
        country: "US",
        state: "NY",
        display_address: ["58 Henry St", "New York, NY 10002"],
      },
      phone: "+12129627032",
      display_phone: "(212) 962-7032",
      distance: 802.5224269471269,
      business_hours: [
        {
          open: [
            {
              is_overnight: false,
              start: "0730",
              end: "1530",
              day: 0,
            },
            {
              is_overnight: false,
              start: "0730",
              end: "1530",
              day: 1,
            },
            {
              is_overnight: false,
              start: "0730",
              end: "1530",
              day: 2,
            },
            {
              is_overnight: false,
              start: "0730",
              end: "1530",
              day: 3,
            },
            {
              is_overnight: false,
              start: "0730",
              end: "1530",
              day: 4,
            },
            {
              is_overnight: false,
              start: "0730",
              end: "1530",
              day: 5,
            },
            {
              is_overnight: false,
              start: "0730",
              end: "1530",
              day: 6,
            },
          ],
          hours_type: "REGULAR",
          is_open_now: true,
        },
      ],
      attributes: {
        business_temp_closed: null,
        menu_url: "",
        open24_hours: null,
        waitlist_reservation: null,
      },
    },
    {
      id: "R3fMQtSL0MrMUyW_Q32oNw",
      alias: "naya-new-york-58",
      name: "NAYA",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/GuU7TKZPSiBh0jX6knAcvg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/naya-new-york-58?adjust_creative=57XI6Kzufv1Z91q9LwdlrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=57XI6Kzufv1Z91q9LwdlrQ",
      review_count: 195,
      categories: [
        {
          alias: "mideastern",
          title: "Middle Eastern",
        },
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
      ],
      rating: 4.2,
      coordinates: {
        latitude: 40.7021564536913,
        longitude: -74.01253591140323,
      },
      transactions: ["pickup", "delivery"],
      price: "$",
      location: {
        address1: "1 New York Plz",
        address2: "",
        address3: "",
        city: "New York",
        zip_code: "10004",
        country: "US",
        state: "NY",
        display_address: ["1 New York Plz", "New York, NY 10004"],
      },
      phone: "+12127608888",
      display_phone: "(212) 760-8888",
      distance: 1585.7246722348953,
      business_hours: [
        {
          open: [
            {
              is_overnight: false,
              start: "1030",
              end: "2000",
              day: 0,
            },
            {
              is_overnight: false,
              start: "1030",
              end: "2000",
              day: 1,
            },
            {
              is_overnight: false,
              start: "1030",
              end: "2000",
              day: 2,
            },
            {
              is_overnight: false,
              start: "1030",
              end: "2000",
              day: 3,
            },
            {
              is_overnight: false,
              start: "1030",
              end: "1700",
              day: 4,
            },
          ],
          hours_type: "REGULAR",
          is_open_now: true,
        },
      ],
      attributes: {
        business_temp_closed: null,
        menu_url: "https://www.eatnaya.com/the-menu/",
        open24_hours: null,
        waitlist_reservation: null,
      },
    },
    {
      id: "XPbcjRWxumT4ZQr-7uqOAw",
      alias: "los-tacos-no-1-new-york-10",
      name: "Los Tacos No.1",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/4abEK0VBrLTkP9hUWAY66g/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/los-tacos-no-1-new-york-10?adjust_creative=57XI6Kzufv1Z91q9LwdlrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=57XI6Kzufv1Z91q9LwdlrQ",
      review_count: 251,
      categories: [
        {
          alias: "tacos",
          title: "Tacos",
        },
      ],
      rating: 4.6,
      coordinates: {
        latitude: 40.726157,
        longitude: -73.9946634,
      },
      transactions: [],
      price: "$",
      location: {
        address1: "340 Lafayette St",
        address2: "",
        address3: null,
        city: "New York",
        zip_code: "10012",
        country: "US",
        state: "NY",
        display_address: ["340 Lafayette St", "New York, NY 10012"],
      },
      phone: "",
      display_phone: "",
      distance: 2299.676432988154,
      business_hours: [
        {
          open: [
            {
              is_overnight: false,
              start: "1100",
              end: "2200",
              day: 0,
            },
            {
              is_overnight: false,
              start: "1100",
              end: "2200",
              day: 1,
            },
            {
              is_overnight: false,
              start: "1100",
              end: "2200",
              day: 2,
            },
            {
              is_overnight: false,
              start: "1100",
              end: "2200",
              day: 3,
            },
            {
              is_overnight: false,
              start: "1100",
              end: "2200",
              day: 4,
            },
            {
              is_overnight: false,
              start: "1100",
              end: "2200",
              day: 5,
            },
            {
              is_overnight: false,
              start: "1100",
              end: "2100",
              day: 6,
            },
          ],
          hours_type: "REGULAR",
          is_open_now: true,
        },
      ],
      attributes: {
        business_temp_closed: null,
        menu_url: "https://www.lostacos1.com/menus/",
        open24_hours: null,
        waitlist_reservation: null,
      },
    },
  ],
  total: 15000,
  region: {
    center: {
      longitude: -73.99429321289062,
      latitude: 40.70544486444615,
    },
  },
};

export const businessDetails = {
  alias: "golden-boy-pizza-hamburg",
  categories: [
    {
      alias: "pizza",
      title: "Pizza",
    },
    {
      alias: "food",
      title: "Food",
    },
  ],
  coordinates: {
    latitude: 41.7873382568359,
    longitude: -123.051551818848,
  },
  display_phone: "(415) 982-9738",
  distance: 4992.437696561071,
  id: "QPOI0dYeAl3U8iPM_IYWnA",
  image_url:
    "https://yelp-photos.yelpcorp.com/bphoto/b0mx7p6x9Z1ivb8yzaU3dg/o.jpg",
  is_claimed: false,
  is_closed: true,
  date_opened: "",
  date_closed: "",
  location: {
    address1: "James",
    address2: "Street",
    address3: "68M",
    city: "Los Angeles",
    country: "US",
    display_address: ["James", "Street", "68M", "Los Angeles, CA 22399"],
    state: "CA",
    zip_code: "22399",
  },
  name: "Golden Boy Pizza",
  phone: "+14159829738",
  photos: [
    "https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg",
    "https://s3-media4.fl.yelpcdn.com/bphoto/FmXn6cYO1Mm03UNO5cbOqw/o.jpg",
    "https://s3-media4.fl.yelpcdn.com/bphoto/HZVDyYaghwPl2kVbvHuHjA/o.jpg",
  ],
  photo_details: [
    {
      photo_id: "CPc91bGzKBe95aM5edjhhQ",
      url: "https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg",
      caption: "Meat",
      width: "710,",
      height: "47,",
      is_user_submitted: "false,",
      user_id: "null,",
      label: "food",
    },
    {
      photo_id: "FmXn6cYO1Mm03UNO5cbOqw",
      url: "https://s3-media4.fl.yelpcdn.com/bphoto/FmXn6cYO1Mm03UNO5cbOqw/o.jpg",
      caption: "Dessert",
      width: 585,
      height: 78,
      is_user_submitted: false,
      user_id: "null,",
      label: "food",
    },
    {
      photo_id: "HZVDyYaghwPl2kVbvHuHjA",
      url: "https://s3-media4.fl.yelpcdn.com/bphoto/HZVDyYaghwPl2kVbvHuHjA/o.jpg",
      caption: "Dessert_2",
      width: 710,
      height: 53,
      is_user_submitted: false,
      user_id: null,
      label: "food",
    },
  ],
  photo_count: 50,
  price: "$",
  rating: 4,
  review_count: 903,
  hours: {
    open: [
      {
        is_overnight: false,
        start: 15,
        end: 130,
        day: 0,
      },
      {
        is_overnight: false,
        start: 630,
        end: 1730,
        day: 1,
      },
      {
        is_overnight: false,
        start: 45,
        end: 500,
        day: 2,
      },
    ],
    hours_type: "REGULAR",
    is_open_now: false,
  },
  special_hours: [
    {
      date: "2019-02-07",
      end: "2000",
      is_closed: null,
      is_overnight: false,
      start: "1600",
    },
  ],
  transactions: ["restaurant_reservation"],
  url: "https://www.yelp.com/biz/golden-boy-pizza-hamburg?adjust_creative=XsIsNkqpLmHqfJ51zfRn3A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=XsIsNkqpLmHqfJ51zfRn3A",
  attributes: {
    business_temp_closed: 1657868400,
    outdoor_seating: false,
    liked_by_vegans: false,
    liked_by_vegetarians: true,
    hot_and_new: "2022-12-10",
  },
  messaging: {
    url: "https://www.yelp.com/raq/AA5cAADa-F9f5DPqZ-PADA?adjust_creative=5374ujususZtKiSNEg7uhg&utm_campaign=yelp_api_v3&utm_medium=api_v3_graphql&utm_source=5374upadasZtCvMLBg7uhg#popup%3Araq",
    use_case_text: "Request a Quote",
    response_rate: 1,
    response_time: 791,
    is_enabled: true,
  },
  yelp_menu_url: "https://www.yelp.com/menu/golden-boy-pizza-hamburg",
  rapc: {
    is_enabled: true,
    is_eligible: true,
  },
};
